DROP TABLE EMPLOYEE;

DROP TABLE DEPT;

CREATE TABLE DEPT(
DEPT_ID NUMBER PRIMARY KEY,
DEPT_NAME VARCHAR(100)
);

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR(500),
LAST_NAME VARCHAR(500),
SALARY NUMBER(10,2),
JOINING_DATE DATE,
DEPARTMENT_DEPT_ID NUMBER REFERENCES DEPT(DEPT_ID)
);



CREATE SEQUENCE EMPLOYEE_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE DEPT_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;